export const LOAD_USERS_LIST = 'LOAD_USERS_LIST';
export const IS_USERS_LIST_LOAD = 'IS_USERS_LIST_LOAD';
export const LOAD_SELECTED_USER = 'LOAD_SELECTED_USER';
export const IS_SELECTED_USER_LOAD = 'IS_SELECTED_USER_LOAD';